//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_DAplicacoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fornece
    {
        public double Preco { get; set; }
        public System.DateTime PrazoEntrega { get; set; }
        public int FornecedorId { get; set; }
        public int StockMateriaisId { get; set; }
    
        public virtual Fornecedor Fornecedor { get; set; }
        public virtual StockMateriais StockMateriais { get; set; }

        public override string ToString()
        {
            return string.Format("Id:{0} Fornecido Por: {1}, Entregue em: {2}, Preço:{3}", StockMateriaisId, Fornecedor.Nome, PrazoEntrega, Preco);
        }
    }
}
