//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_DAplicacoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMateriais
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockMateriais()
        {
            this.Fornece = new HashSet<Fornece>();
            this.Consumo = new HashSet<Consumo>();
        }
    
        public int Id { get; set; }
        public int QuantActual { get; set; }
        public int ConsumoMedioDiario { get; set; }
        public int StockMinimo { get; set; }
        public int PecaArranjoArranjoId { get; set; }
        public int PecaArranjoPecaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fornece> Fornece { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consumo> Consumo { get; set; }
    }
}
